kind: pipeline
name: snowsync
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:

- name: build
  pull: if-not-exists
  image: golang:1.15
  commands:
  - apt update && apt install -y zip
  - mkdir bin
  - make
  - ls -lah bin/
